<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <div class="card-header">
        <h4 class="card-title"><?php $this->show('Bookings'); ?> <small>(<?= count($calendar); ?>)</small></h4>
    </div>

    <?= $this->widget(new GridViewWidget($calendar, array(
        'tableClass' => 'table table-hover table-bordered table-striped',
        'rowAttributes' => array(
            'class' => function($item) use ($entity){
                return $item->getId() == $entity->getId() ? 'table-info' : null;
            }
        ),

        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'start',
                'label' => 'Start date'
            ),

            array(
                'column' => 'end',
                'label' => 'End date'
            ),

            array(
                'column' => 'duration'
            )
        ),

        'actions' => array(
            'edit' => function($item){
                return Icon::edit(
                    $this->url('Booking:Admin:Calendar@editAction', $item->getId()),
                    $this->translate('Edit this item')
                );
            },

            'remove' => function($item){
                return Icon::remove(
                    $this->url('Booking:Admin:Calendar@deleteAction', $item->getId()),
                    $this->translate('Remove this item')
                );
            }
        )
    ))); ?>

    <?php if (empty($calendar)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No items'); ?></h2>
    </div>
    <?php endif; ?>
</div>


<div class="card">
    <div class="card-header">
        <h4 class="card-title"><i class="fas fa-edit"></i> <?php $this->show($title); ?></h4>
    </div>

    <form data-group="item" autocomplete="off">
        <div class="well">
            <?php echo Element::hidden('item[id]', $entity->getId()); ?>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Start date'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('item[start]', $entity->getStart(), array('class' => 'form-control', 'placeholder' => $this->translate('Start date'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('End date'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('item[end]', $entity->getEnd(), array('class' => 'form-control', 'placeholder' => $this->translate('End date'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Comment'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::textarea('item[comment]', $entity->getComment(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </div>

        <?php $this->loadPartial('actions', array(
            'new' => !$entity->getId(),
            'add' => 'Booking:Admin:Calendar@indexAction',
            'edit' => 'Booking:Admin:Calendar@editAction',
            'save' => 'Booking:Admin:Calendar@saveAction',
            'cancel' => 'Booking:Admin:Calendar@indexAction'
        )); ?>

    </form>
</div>